// Code generated by "stringer -linecomment -type ErrCode ./src"; DO NOT EDIT.

package src

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_CODE_OK-0]
	_ = x[ERR_CODE_INVALID_PARAMS-1]
	_ = x[ERR_CODE_TIMEOUT-2]
	_ = x[ERR_CODE_FILE_NOT_EXIST-3]
	_ = x[ERR_CODE_CONN_REFUSE-4]
	_ = x[ERR_CODE_NET_ABNORMAL-5]
}

const _ErrCode_name = "PROCESS OK参数无效超时文件不存在连接被拒绝网络异常"

var _ErrCode_index = [...]uint8{0, 10, 22, 28, 43, 58, 70}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
